/* Generated by Nim Compiler v0.11.3 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Standalone, avr, gcc */
/* Command for C compiler:
   avr-gcc -c  -mmcu=atmega168 -w -O3 -fno-strict-aliasing  -I/data/nick/i/installs/Nim/lib -o /data/nick/i/gitworking/noofac/nim-test/nimcache/blink.o /data/nick/i/gitworking/noofac/nim-test/nimcache/blink.c */
#define NIM_INTBITS 16
#include "nimbase.h"
N_NIMCALL(NI, blank_25018)(NI x);
NIM_EXTERNC N_NOINLINE(void, systemInit)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unsignedInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unsignedDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, blinkInit)(void);
NIM_EXTERNC N_NOINLINE(void, blinkDatInit)(void);

N_NIMCALL(NI, blank_25018)(NI x) {
	NI result;
	NU16 delay;
	NU16 delay2;
	NU8 value;
	NU8* volatile Ddrb;
	NU8* volatile Portb;
{	result = 0;
	delay = 0;
	delay2 = 0;
	value = ((NU8) 0);
	Ddrb = ((NU8*) 36);
	Portb = ((NU8*) 37);
	(*Ddrb) = ((NU8) 255);
	{
		while (1) {
			value = (NU8)((NU8) ~(value));
			delay = ((NU16) 32000);
			{
				while (1) {
					if (!!((delay == ((NI) 0)))) goto LA4;
					delay -= ((NI) 1);
				} LA4: ;
			}
			(*Portb) = value;
		}
	}
	result = ((NI) 0);
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}
void PreMainInner() {
	systemInit();
	stdlib_unsignedDatInit();
	blinkDatInit();
	stdlib_unsignedInit();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit();
	inner = PreMainInner;
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	blinkInit();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	(*inner)();
}

int main(void) {
	NimMain();
	return 0;
}

NIM_EXTERNC N_NOINLINE(void, blinkInit)(void) {
	NI LOC1;
	LOC1 = 0;
	LOC1 = blank_25018(((NI) 3));
}

NIM_EXTERNC N_NOINLINE(void, blinkDatInit)(void) {
}

