/* Generated by Nim Compiler v0.11.3 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Standalone, avr, gcc */
/* Command for C compiler:
   avr-gcc -c -w  -I/data/nick/i/installs/Nim/lib -o /data/nick/i/gitworking/noofac/nim-test/nimcache/blink.o /data/nick/i/gitworking/noofac/nim-test/nimcache/blink.c */
#define NIM_INTBITS 16
#include "nimbase.h"
N_NIMCALL(void, blank_25018)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
NIM_EXTERNC N_NOINLINE(void, systemInit)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unsignedInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unsignedDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, blinkInit)(void);
NIM_EXTERNC N_NOINLINE(void, blinkDatInit)(void);

//static N_INLINE(void, nimFrame)(TFrame* s) {}

//static N_INLINE(void, popFrame)(void) {}

N_NIMCALL(void, blank_25018)(void) {
	NU16 delay;
	NU8 value;
	NU8* volatile Ddrb;
	NU8* volatile Portb;
	nimfr("blank", "blink.nim")
	nimln(15, "blink.nim");
	delay = ((NU16) 1000);
	nimln(16, "blink.nim");
	value = ((NU8) 0);
	nimln(17, "blink.nim");
	Ddrb = ((NU8*) 36);
	nimln(18, "blink.nim");
	Portb = ((NU8*) 37);
	nimln(29, "blink.nim");
	(*Portb) = ((NU8) 255);
	{
		nimln(31, "blink.nim");
		while (1) {
			nimln(32, "blink.nim");
			(*Portb) = value;
			nimln(33, "blink.nim");
			value = (NU8)((NU8) ~(value));
			nimln(34, "blink.nim");
			delay = ((NU16) 32000);
			{
				nimln(35, "blink.nim");
				while (1) {
					if (!!((delay == ((NI) 0)))) goto LA4;
					nimln(36, "blink.nim");
					delay -= ((NI) 1);
				} LA4: ;
			}
		}
	}
	popFrame();
}
void PreMainInner() {
	systemInit();
	stdlib_unsignedDatInit();
	blinkDatInit();
	stdlib_unsignedInit();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit();
	inner = PreMainInner;
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	blinkInit();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	(*inner)();
}

int main(void) {
	NimMain();
	return 0;
}

NIM_EXTERNC N_NOINLINE(void, blinkInit)(void) {
	nimfr("blink", "blink.nim")
	nimln(39, "blink.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, blinkDatInit)(void) {
}

#include "nimcache/stdlib_system.c"
#include "nimcache/stdlib_unsigned.c"
