/* Generated by Nim Compiler v0.11.3 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Standalone, avr, gcc */
/* Command for C compiler:
   avr-gcc -c -w  -I/data/nick/i/installs/Nim/lib -o /data/nick/i/gitworking/noofac/nim-test/nimcache/blink.o /data/nick/i/gitworking/noofac/nim-test/nimcache/blink.c */
#include <stdint.h>
int main(void) {
  int delay;

 (*(volatile uint8_t *)((0x04) + 0x20)) |= (1 << (5));

 while(1) {

  (*(volatile uint8_t *)((0x05) + 0x20)) |= (1 << (5));

  for(delay = 0; delay < 1000; delay++);


  (*(volatile uint8_t *)((0x05) + 0x20)) &= ~(1 << (5));

  for(delay = 0; delay < 1000; delay++);
 }
}

#include "nimcache/stdlib_system.c"
#include "nimcache/stdlib_unsigned.c"
