/* Generated by Nim Compiler v0.11.3 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Standalone, avr, gcc */
/* Command for C compiler:
   avr-gcc -c -w  -I/data/nick/i/installs/Nim/lib -o /data/nick/i/gitworking/noofac/nim-test/nimcache/blink.o /data/nick/i/gitworking/noofac/nim-test/nimcache/blink.c */
#define NIM_INTBITS 16
#include "nimbase.h"
int cmdCount;
char** cmdLine;
char** gEnv;



#define PORTB (*(volatile uint8_t*)(0x05 + 0x20))

static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
N_CDECL(void, NimMain)(void);
N_CDECL(void, NimMainInner)(void);
NIM_EXTERNC N_NOINLINE(void, systemInit)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unsignedInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unsignedDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, blinkInit)(void);
NIM_EXTERNC N_NOINLINE(void, blinkDatInit)(void);

NU16 delay_25019;
NU8 value_25020;
NU8* volatile Ddrb_25021;
NU8* volatile Portb_25022;

N_CDECL(void, flash)(void);
//void flash();

#include <stdint.h>
int main(void) {
	NimMain();
	return 0;
//    flash();

 
}

N_CDECL(void, flash)(void) {
  int delay;
//(*(volatile uint8_t *)((0x04) + 0x20)) |= (1 << (5));

 while(1) {


  for(delay = 0; delay < 32000; delay++) ;

     PORTB = PORTB ^ (1 << 5);

 }
}

void PreMainInner() {
	systemInit();
	stdlib_unsignedDatInit();
	blinkDatInit();
	stdlib_unsignedInit();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit();
	inner = PreMainInner;
	(*inner)();
//	PreMainInner();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	(*inner)();
//	NimMainInner();
}



//static N_INLINE(void, nimFrame)(TFrame* s) {
//}

//static N_INLINE(void, popFrame)(void) {
//}

NIM_EXTERNC N_NOINLINE(void, blinkInit)(void) {
NU16 delay_25019;
NU8 value_25020;
NU8* volatile Portb_25022;
	nimfr("blink", "blink.nim")
	nimln(10, "blink.nim");
	delay_25019 = ((NU16) 1000);
	nimln(11, "blink.nim");
	value_25020 = ((NU8) 0);
	nimln(12, "blink.nim");
	Ddrb_25021 = ((NU8*) 36);
	nimln(13, "blink.nim");
	Portb_25022 = ((NU8*) 37);
	nimln(23, "blink.nim");
	(*Ddrb_25021) = ((NU8) 0);
	{
		nimln(25, "blink.nim");
		while (1) {
			nimln(26, "blink.nim");
			(*Portb_25022) = value_25020;
			//PORTB = value_25020;
		    //if (value_25020 == 0)
		    //flash();
			//PORTB = PORTB ^ (1 << 5);
			
//			for(delay_25019 = 0; delay_25019 < 32000; delay_25019++);
			nimln(27, "blink.nim");
			value_25020 = (NU8)((NU8) ~(value_25020));
			nimln(28, "blink.nim");
			delay_25019 = 32000;//((NU16)0);
			{

				nimln(29, "blink.nim");
//			if (delay_25019 == 0)
//			    flash();
				while (1) {
					if (!!((delay_25019 == ((NI) 0)))) goto LA4;
//					if (delay_25019 == 0x6666) goto LA4;
					nimln(30, "blink.nim");
					delay_25019 -= ((NI) 1);
				} LA4: ;
			}


		}
	}
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, blinkDatInit)(void) {
}
N_CDECL(void, NimMainInner)(void) {
	blinkInit();
}


#include "nimcache/stdlib_system.c"
#include "nimcache/stdlib_unsigned.c"

